'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Pencil,Trash2,Users,Search,Check,X} from 'lucide-react';
import {LeadSchema,type Lead} from '@/lib/leads';
export default function Leads(){
 const [leads,setLeads]=useState<Lead[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[name,setName]=useState(''),[editing,setEditing]=useState<Lead|null>(null),[search,setSearch]=useState(''),[notice,setNotice]=useState('');
 const addButton=useRef<HTMLButtonElement>(null);
 async function load(){setError('');try{const r=await fetch('/api/leads');const data=await r.json() as Lead[]&{error?:string};if(!r.ok)throw new Error(data.error||'Could not load leads.');setLeads(data)}catch(e){setError((e as Error).message)}finally{setLoaded(true)}}
 useEffect(()=>{load()},[]);
 async function save(lead:Lead){const parsed=LeadSchema.safeParse(lead);if(!parsed.success){setError(parsed.error.issues[0].message);return}setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/leads',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...parsed.data,revision:lead.revision})});const data=await r.json() as Lead&{error?:string};if(!r.ok)throw new Error(data.error||'Could not save lead.');setLeads(prev=>[...prev.filter(x=>x.id!==lead.id),data]);if(lead.revision===0){setName('');setAdding(false);addButton.current?.focus()}else setEditing(null);setNotice('Lead saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(lead:Lead){if(!confirm(`Remove ${lead.name} from your leads?`))return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/leads',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:lead.id,revision:lead.revision})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Could not remove lead.');setLeads(prev=>prev.filter(x=>x.id!==lead.id));if(editing?.id===lead.id)setEditing(null);setNotice('Lead removed.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const shown=leads.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 return <section aria-label="Potential client leads"><div className="title-row"><div><h1>Leads</h1><p>Potential clients for your studio.</p></div><button ref={addButton} className="primary" disabled={busy} onClick={()=>{setAdding(true);setEditing(null);setError('')}}><Plus size={18}/> New lead</button></div>
 {error&&<div className="error" role="alert">{error} <button disabled={busy} onClick={load}>Reload leads</button></div>}
 {adding&&<form className="lead-add" onSubmit={e=>{e.preventDefault();save({id:crypto.randomUUID(),name,revision:0})}}><label>Client name<input autoFocus required maxLength={120} value={name} disabled={busy} placeholder="Artist or band name" onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Add lead'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setAdding(false);setName('');addButton.current?.focus()}}>Cancel</button></form>}
 <div className="list-top"><span className="lead-count">{leads.length} {leads.length===1?'lead':'leads'}</span><div className="search"><Search size={16}/><input aria-label="Search leads" placeholder="Search client names…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 {!loaded?<div className="empty">Loading leads…</div>:shown.length===0?<div className="empty"><div className="empty-icon"><Users size={28}/></div><h2>{search?'No matching leads':'No leads yet'}</h2><p>{search?'Try another client name.':'Add a client name to start your list.'}</p></div>:<div className="leads-list"><div className="leads-heading">CLIENT NAME</div>{shown.map(lead=><div className="lead-row" key={lead.id}>{editing?.id===lead.id?<form className="lead-edit" onSubmit={e=>{e.preventDefault();save(editing)}}><input aria-label="Client name" autoFocus required maxLength={120} disabled={busy} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><button className="secondary" disabled={busy} aria-label="Save client name"><Check size={16}/> Save</button><button type="button" className="lead-icon" disabled={busy} aria-label="Cancel rename" onClick={()=>setEditing(null)}><X size={17}/></button></form>:<><span className="lead-avatar"><Users size={17}/></span><strong>{lead.name}</strong><button className="lead-icon" disabled={busy} aria-label={`Rename ${lead.name}`} title="Rename client" onClick={()=>{setEditing({...lead});setAdding(false)}}><Pencil size={16}/></button><button className="lead-icon" disabled={busy} aria-label={`Remove ${lead.name}`} title="Remove lead" onClick={()=>remove(lead)}><Trash2 size={16}/></button></>}</div>)}</div>}
 <p className="lead-notice" role="status">{notice}</p></section>;
}
